apiVersion: v1
kind: Service
metadata:
  labels:
    name: dave
    layer: frontend
    project: dave
  name: dave
  namespace: ttsave
spec:
  ports:
    - name: https
      port: 443
      targetPort: 8181
    - name: http
      port: 80
      targetPort: 8080
  selector:
    name: dave
  type: LoadBalancer
