apiVersion: v1
kind: ConfigMap
metadata:
  name: dave-config
  namespace: ttsave
  labels:
    app: dave
    layer: frontend
    project: dave
data:
  log.level: "INFO"
  db.name: "DAVe-TTSave"
  db.connection_url: "mongodb://mongo-svc-1.database:27017,mongo-svc-2.database:27017,mongo-svc-3.database:27017/?replicaSet=my_replica_set"
  #db.hostname: "mongo.default"
  #db.port: "27017"
  http.enable: "TRUE"
  http.compression: "TRUE"
  http.auth: "TRUE"
  http.redirect: "TRUE"
  http.redirectUri: "ab1f0ccb1cdd711e6aabc02528b4ec82-2090304637.eu-west-1.elb.amazonaws.com"
  http.cors: "TRUE"
  http.cors_origin: "*"
