export const ROUTE_NAMES = {
    DASHBOARD: 'dashboard',
    LOGIN    : 'login',

    DASHBOARD_MARGIN_REQUIREMENT_OVERVIEW: 'marginRequirementOverview',
    DASHBOARD_POSITION_LEVEL_RISK        : 'positionLevelRisk',
    DASHBOARD_INITIAL_MARGIN             : 'initialMargin',

    ACCOUNT_MARGIN_LATEST : 'accountMarginLatest',
    ACCOUNT_MARGIN_HISTORY: 'accountMarginHistory',

    LIQUI_GROUP_MARGIN_LATEST : 'liquiGroupMarginLatest',
    LIQUI_GROUP_MARGIN_HISTORY: 'liquiGroupMarginHistory',

    VARIATION_PREMIUM_MARGIN_LATEST : 'variPremiumMarginLatest',
    VARIATION_PREMIUM_MARGIN_HISTORY: 'variPremiumMarginHistory',

    INITIAL_MARGIN_LATEST : 'initialMarginLatest',
    INITIAL_MARGIN_HISTORY: 'initialMarginHistory',

    POOL_MARGIN_LATEST : 'poolMarginLatest',
    POOL_MARGIN_HISTORY: 'poolMarginHistory',

    POSITION_REPORTS_LATEST : 'positionReportLatest',
    POSITION_REPORTS_HISTORY: 'positionReportHistory',

    RISK_LIMIT_UTILIZATION_LATEST : 'riskLimitUtilizationLatest',
    RISK_LIMIT_UTILIZATION_HISTORY: 'riskLimitUtilizationHistory'
};

const dashboardRoute = '/' + ROUTE_NAMES.DASHBOARD;

export const ROUTES = {
    ROOT     : '/',
    DASHBOARD: dashboardRoute,
    LOGIN    : '/' + ROUTE_NAMES.LOGIN,

    DASHBOARD_MARGIN_REQUIREMENT_OVERVIEW: dashboardRoute + '/' + ROUTE_NAMES.DASHBOARD_MARGIN_REQUIREMENT_OVERVIEW,
    DASHBOARD_POSITION_LEVEL_RISK        : dashboardRoute + '/' + ROUTE_NAMES.DASHBOARD_POSITION_LEVEL_RISK,
    DASHBOARD_INITIAL_MARGIN             : dashboardRoute + '/' + ROUTE_NAMES.DASHBOARD_INITIAL_MARGIN,

    ACCOUNT_MARGIN_LATEST : '/' + ROUTE_NAMES.ACCOUNT_MARGIN_LATEST,
    ACCOUNT_MARGIN_HISTORY: '/' + ROUTE_NAMES.ACCOUNT_MARGIN_HISTORY,

    LIQUI_GROUP_MARGIN_LATEST : '/' + ROUTE_NAMES.LIQUI_GROUP_MARGIN_LATEST,
    LIQUI_GROUP_MARGIN_HISTORY: '/' + ROUTE_NAMES.LIQUI_GROUP_MARGIN_HISTORY,

    VARIATION_PREMIUM_MARGIN_LATEST : '/' + ROUTE_NAMES.VARIATION_PREMIUM_MARGIN_LATEST,
    VARIATION_PREMIUM_MARGIN_HISTORY: '/' + ROUTE_NAMES.VARIATION_PREMIUM_MARGIN_HISTORY,

    INITIAL_MARGIN_LATEST : '/' + ROUTE_NAMES.INITIAL_MARGIN_LATEST,
    INITIAL_MARGIN_HISTORY: '/' + ROUTE_NAMES.INITIAL_MARGIN_HISTORY,

    POOL_MARGIN_LATEST : '/' + ROUTE_NAMES.POOL_MARGIN_LATEST,
    POOL_MARGIN_HISTORY: '/' + ROUTE_NAMES.POOL_MARGIN_HISTORY,

    POSITION_REPORTS_LATEST : '/' + ROUTE_NAMES.POSITION_REPORTS_LATEST,
    POSITION_REPORTS_HISTORY: '/' + ROUTE_NAMES.POSITION_REPORTS_HISTORY,

    RISK_LIMIT_UTILIZATION_LATEST : '/' + ROUTE_NAMES.RISK_LIMIT_UTILIZATION_LATEST,
    RISK_LIMIT_UTILIZATION_HISTORY: '/' + ROUTE_NAMES.RISK_LIMIT_UTILIZATION_HISTORY
};